### ISSUE TITLE
level 3 opacity to 100

### ISSUE THREAD

**Issue by grena** [pierallard/ldjam45#18]
Parce que sur mon PC chez moi, ça fait ça:

![](https://i.imgur.com/AowPIQ5.png)

Et que du coup... JE VOIS TOUT

**Comment by pierallard** [comment]
En mode debug, il est à 0.9 :) fous le DEBUG à false

**Comment by grena** [comment]
Ahh yes merci! je l'ai passé de 0.985 à 0.99 en non debug, sur mon écran on voyait encore un peu trop!
